### ISSUE TITLE
PHP 7  Issue

### ISSUE THREAD

**Issue by maximusblade** [spatie/laravel-twitter-streaming-api#11]
Is this a known issue with PHP 7 ?

  [InvalidArgumentException]
  Could not find package spatie/laravel-twitter-streaming-api at any version matching your PHP version 5.6.4.0

![image](https://user-images.githubusercontent.com/13944020/29211299-8a986b8a-7e98-11e7-8561-fc2722ff74a6.png)

**Comment by freekmurze** [comment]
There's something wrong with the Laravel installer.

Remove the platform key in `composer.json` and try installing the package again.

**Comment by maximusblade** [comment]
BOOM!
thank you that worked.
