### ISSUE TITLE
Listen to lists of twitter users

### ISSUE THREAD

**Issue by VerzatileTom** [spatie/laravel-twitter-streaming-api#12]
Love this. Perhaps you can create a method to listen for the given lists of users.

**Comment by VerzatileTom** [comment]
would also be nice if it can chain methods like

```php
TwitterStreamingApi::publicStream()
        ->whenHears('#laravel', function (array $tweet) {
            // codes
        })
        ->whenHears('#vuejs', function (array $tweet) {
            // codes
        })
        ->startListening();
```

**Comment by freekmurze** [comment]
> Love this. Perhaps you can create a method to listen for the given lists of users.

I don't think Twitter allows this. You'll find that it'll kill streams whenever you try to open multiple ones

> would also be nice if it can chain methods like

I'd probably accept a PR that adds this to the package.

**Comment by varunchopraWB** [comment]
I have been able to use an array for this. Dunno if thats how its intended to be used?

```
$hashtagArray = array("#Tesla", "#stocks", "#ValentinesDay");
    	
        TwitterStreamingApi::publicStream()
            ->whenHears($hashtagArray, function (array $tweet) {
            	dump("{$tweet['user']['screen_name']} tweeted {$tweet['text']}");
            })
            ->startListening();
```
