### ISSUE TITLE
HTTP ERROR 420: Enhance Your Calm (Exceeded connection limit for user).

### ISSUE THREAD

**Issue by varunchopraWB** [spatie/laravel-twitter-streaming-api#20]
May i ask how we could overcome the connection limit? I can only listen to 2 hashtags by initiating 2 different commands which holds 2 different hashtags. 

Is there an efficient way to do this where i can listen to more than 2?

Thank you!

**Comment by AlexVanderbist** [comment]
Hi! 

If I recall correctly you can use and of the standard query rules and filters in `whenHears()`. 

```php
->whenHears('#love OR #hate', ...)
```

Have a look at https://developer.twitter.com/en/docs/tweets/rules-and-filtering/overview/standard-operators.html for more information.

**Comment by varunchopraWB** [comment]
Right, i undertand i can create an array and pass that into the "whenHears" BUT once i have "heard" the tweet, i cant seem to distinguish between tweets based on which hash tag was listened to.

Showing you code below. May i ask if you have solved something like this before?

`


              $hashtagArray = array("#hashtag1", "#hashtag2");
               TwitterStreamingApi::publicStream()
	            ->whenHears($hashtagArray, function (array $tweet) {
	            
	            	if ("#hashtag1") {
	            		$this->storethisTweet_ForHashTAG1($tweet);
	            	}
	            	if ("#hashtag2") {
	            		$this->storethisTweet_ForHashTAG($tweet);
	            	}
	            	
	            	dump("{$tweet['user']['screen_name']}");
	
	            	dump("{$tweet['text']}");
	
	            })
	            ->startListening();
`

**Comment by AlexVanderbist** [comment]
You can simply check if the tweet contains one of the hashtags by looking at the `$tweet` properties. You'll find all hashtags listed in `$tweet['entities']['hashtags']`.

**Comment by varunchopraWB** [comment]
Thanks guys.

**Comment by varunchopraWB** [comment]
Thank you.
