### ISSUE TITLE
A question on executing commands per Hashtag

### ISSUE THREAD

**Issue by varunchopraWB** [spatie/laravel-twitter-streaming-api#21]
i understand that i can create an array and pass that into the "whenHears" BUT once i have "heard" the tweet, i cant seem to distinguish between tweets based on which hash tag was listened to.

Showing you code below. May i ask if you have solved something like this before?

```
           $hashtagArray = array("#hashtag1", "#hashtag2");
            TwitterStreamingApi::publicStream()
             ->whenHears($hashtagArray, function (array $tweet) {
            
            	if ("#hashtag1") {
            		$this->storethisTweet_ForHashTAG1($tweet);
            	}
            	if ("#hashtag2") {
            		$this->storethisTweet_ForHashTAG2($tweet);
            	}
            	
            	dump("{$tweet['user']['screen_name']}");

            	dump("{$tweet['text']}");

            })
            ->startListening();
```

Is there a way to do that?

Thanks for all your help!

**Comment by freekmurze** [comment]
Probably there's a property on `$tweet` where you can see the full text (including hashtags) of the tweet. Don't know the property name by heart though. Find out by wrapping `$tweet` in a `die()` statement.

**Comment by varunchopraWB** [comment]
Thank you.
