### ISSUE TITLE
Required parameter $params follows optional parameter $method

### ISSUE THREAD

**Issue by felixdorn** [spatie/laravel-twitter-streaming-api#35]
This issue also occurs in the CI so i guess it's more of an overlooked update of Phirehose that broke something rather than a real bug in the package's code.

I can submit a PR.

**Comment by freekmurze** [comment]
Feel free to PR a fix

**Comment by felixdorn** [comment]
The problem is 

```php
protected function prepareParameters($method = null, $url = null, array $params)
```

Which makes PHP8 throw a warning and everything blows up.

The problem is that Phirehose is not maintained and I can't simply submit a PR. My idea would be to just take Phirehose's code and add it directly to the package. But Phirehose is GPL licensed and to sum up this [thread](https://opensource.stackexchange.com/questions/6062/using-gpl-library-with-mit-licensed-code). It's not exactly legal (at least as far as I understand it). My question is would you accept a PR that uses another library or just a modern rewrite of Phirehose (in a GPL compliant way) in the package. This would probably make the package a little bigger (if there is no package like phirehose) and definitely slightly harder to maintain.

**Comment by freekmurze** [comment]
I'm thinking that the easiest way forward would be to fork the phirehose package to another repo, modernise it there, and require it from this package. That way, this package would remain small and simple.

**Comment by felixdorn** [comment]
Yeah that's an even better approach, thanks! I've started working on it here: https://github.com/redwebcreation/phirehose for reference.

**Comment by felixdorn** [comment]
After reading my message again, i believe my approach was stupid. I'm gonna send a PR that fixes this package, without changing the public API and make a new package on my own that supports more advanced features for those who need it.

**Comment by felixdorn** [comment]
Once, https://github.com/spatie/twitter-streaming-api/pull/30 gets merged. I'll PR the small changes needed here.

**Comment by felixdorn** [comment]
For the record, https://github.com/spatie/laravel-twitter-streaming-api/pull/36

**Comment by jayenne** [comment]
Hi, thanks for keeping this current, it's integral to my little project and i'd be in trouble if it faded away. of course, I have a question regarding the new API...
Can I add `fields` to my whereHeres query or is there another way?
- currently I am only getting the default `id` and `tweet` and would like a few more from the `root-list` probably not the entire `object` but some people may.
