### ISSUE TITLE
A few questions about whenHears()

### ISSUE THREAD

**Issue by jayenne** [spatie/laravel-twitter-streaming-api#41]
I have an app listening via whenHears() and would love a conversation with you as I have some question I just can't find answers too...
A: Is "whenHears" subject to Twitter rate limiting? and if so...
- Which 'rate limit' does this fall within?
- Does it count how many times it has a positive "hearing" or count every request "have you heard"
- Does "whenHears" return every occurance of a positive "hearing" as a singular result or, would it, in extreemly busy instances, would it return an array of all "hearings" since the last positice result?

I am developing an app that listens to one specific @mention but needs to never mis one even in exptreemly busy periods. are my expectations reasonable/expected behaviour within this streamer or should I be considering at another approach?

I know I'm asking a lot but am also really greatful of any help and advice any of you may have.

**Comment by felixdorn** [comment]
Twitter caps the limit of tweets pulled at 500k per month.

You can create a connection as much as 50 times per 15 minutes which should be more than enough.

**Comment by felixdorn** [comment]
Does "whenHears" return every occurance of a positive "hearing" as a singular result or, would it, in extreemly busy instances, would it return an array of all "hearings" since the last positice result?

There's no special case for "extremely busy instances" but it will work fine.

**Comment by jayenne** [comment]
Thank you Felix, I appreciate your feedback. Can I ask what constitutes a connection? is each time I run my Twitter listener command? or is it connected to the number of tweets I can hear?

I ask because I am hitting the “429 connection limit“ whilst testing and tweaking my code and this sounds quite like it could be the cause.
*and is not a problem as it’s only a few mins before it ticks over and let’s me connect again.

It would be more of a problem if “a connection” Was linked to the number of tweets and I could only hear 50weeks per 15mins? …which, thanks to you now don’t think is the case but feel I still need to ask.

Regards,
Jayenne

On 5 Oct 2021, at 15:51, Félix Dorn ***@***.***> wrote:

﻿

Twitter caps the limit of tweets pulled at 500k per month.

You can create a connection as much as 50 times per 15 minutes which should be more than enough.—

**Comment by felixdorn** [comment]
Everytime you restart a listener, it does use a new connection. I had the same problems while developing but there's really nothing you can do about it.

`50 / 15 minutes` = `1 / 15 seconds`

**Comment by jayenne** [comment]
Thanks very much. Appreciated

Regards,
Jayenne

On 5 Oct 2021, at 16:28, Félix Dorn ***@***.***> wrote:

﻿

Everytime you restart a listener, it does use a new connection. I had the same problems while developing but there's really nothing you can do about it.

50 / 15 minutes = 1 / 15 seconds
