### ISSUE TITLE
Reliability Issues

### ISSUE THREAD

**Issue by felixdorn** [spatie/laravel-twitter-streaming-api#43]
About a year ago, I worked on updating this package for the new Twitter API. To achieve this, I had to create a new package to replace the old one "fennb/phirehose". However, as I'm now aware, there are a lot of things wrong with `spatie/laravel-twitter-streaming-api` and its brother `spatie/twitter-streaming-api` and their big brother `redwebcreation/twitter-stream-api`. You can not reliably use them, there is an issue that sometimes occur when Twitter sends JSON that will just close the stream, as well as other errors and inconsistencies that are very hard to test and patch as we need to hit the live API.

These bugs are now fixed in the latest release of `redwebcreation/twitter-stream-api`. I do not use anymore the two other packages from Spatie. Their API was great for the V1 but not the V2. For this reason, I'm not going to try to port the changes over.

I recommend simply switching or PRing a fix yourself. I can answer any questions you may have in doing so.

@freekmurze A warning may be needed in the README of the two packages.

**Comment by simonbuehler** [comment]
👍 great you fixed underlying stuff in  `redwebcreation/twitter-stream-api` and according to https://github.com/spatie/twitter-streaming-api/network/dependencies it already uses `redwebcreation/twitter-stream-api` but should be bumped to 1.0 with your fixes i guess?

**Comment by felixdorn** [comment]
Well, it's more than that, bumping isn't enough, a new API is needed. That means a new major version. That means rethinking the API to better it. I've already done that once with the underlying package (mine). I don't feel like I need to do it again.
