### ISSUE TITLE
Feature Request: Stop Listening

### ISSUE THREAD

**Issue by lukecurtis93** [spatie/laravel-twitter-streaming-api#8]
This is such a great api package for twitter.

As we know the stream never closes, so if I called it via a get request in my routes (not that I should ideally be doing that anyway) it would loop forever.

Maybe a stop listening feature that kills any open connections and streams.

**Comment by freekmurze** [comment]
Don't really know how to do this in a clean way. 

I'm also thinking that most users do want a never ending listen.

I'd accept a PR for this if this can be implemented real simple.

**Comment by dillingham** [comment]
@freekmurze its like horizon:terminate you need a command to stop and refresh code upon deploy
